data:
  dataset_name: "programming_language"
  batch_size: 32
  validation_split: 0.1
  normalize: false
  min_samples_per_class: 200
  lightweight: false  # true: 軽量化モデル（5000特徴量）, false: フル機能モデル

model:
  model_type: "logistic_regression"
  parameters:
    max_iter: 1000
    solver: "saga"
    n_jobs: -1

training:
  epochs: 10
  learning_rate: 0.001
  early_stopping: true
  patience: 5

experiment_name: "classify-programing_language_baseline"
random_seed: 42

logging:
  level: "INFO"
  log_file: "experiments/logs/experiment.log"